=== EB-Omar/Library/Books/livre.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <!-- balises isolées --> <xsd:element name="titre" type="xsd:string"/> 
  <xsd:element
    name="description" type="xsd:string"/> <xsd:element name="cover" type="xsd:string"/>
    <xsd:element name="date" type="xsd:string"/> 
  <!-- balises d'un auteur --> <xsd:element name="nom" type="xsd:string"/> <xsd:element
    name="prenom" type="xsd:string"/> <xsd:element name="nationalité" type="xsd:string"/>
  <!-- balise auteur --> <xsd:element name="auteur"> <xsd:complexType> <xsd:sequence> <xsd:element
          ref="nom"/> <xsd:element ref="prenom"/> <xsd:element ref="nationalité"/> </xsd:sequence>
    </xsd:complexType> </xsd:element>     <xsd:element name="titre_s"
    type="xsd:string"/> <xsd:element name="paragraphe"/>
  <!-- balise sction --> <xsd:element name="section"> <xsd:complexType> <xsd:sequence> <xsd:element
          ref="titre_s"/> <xsd:element ref="paragraphe" maxOccurs="unbounded"/> </xsd:sequence>
    </xsd:complexType> </xsd:element> <xsd:element name="livre"> <xsd:complexType> <xsd:sequence>
          <xsd:element ref="auteur"/> <xsd:element ref="titre"/> <xsd:element ref="description"/>
          <xsd:element ref="cover"/> <xsd:element ref="date"/> 
          <xsd:element ref="section"/> </xsd:sequence> </xsd:complexType> </xsd:element> </xsd:schema>

=== EB-Omar/Library/Books/livre5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre5 -->
    
    <auteur>
        <nom>Amélie</nom>
        <prenom>Nothomb</prenom>
        <nationalité>Belge</nationalité>
    </auteur>
    <titre>Soif</titre>
    <description>Roman</description>
    <cover>livre5.jpg</cover>
    <date>2019</date>
    
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>
            La romancière se glisse dans la tête de Jésus-Christ depuis son procès jusqu'à la résurrection, et raconte à la première personne les réflexions du Christ sur son Père, le corps, l'amour, la jouissance, l'ingratitude humaine, la souffrance, l'espérance, la foi ou encore la mort. Le temps de la Passion ravive la mémoire d’événements, d’expériences, de rencontres présentes dans le Nouveau Testament sous l'oeil de Jésus, qui raconte « son » Judas, ou encore le « best of » de ses miracles2.
            
            A propos de l'écriture du roman, elle explique que : « Tous les livres que j’ai écrits avant celui-ci étaient des exercices de musculation destinés à m’entraîner à écrire ce livre. Il y avait préméditation, je savais que je voulais écrire mon livre sur Jésus, que c’était ce qui m’importait. Si je n’ai cessé de repousser l’échéance, c’est que je ne me sentais pas assez musclée, je n’étais pas encore l’athlète de l’écriture que je rêvais d’être. »
        </paragraphe>
        <paragraphe> 
            test  test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test
        </paragraphe>
        
    </section>
</livre>

=== EB-Omar/Library/Books/livre6.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre6 -->
    
    <auteur>
        <nom>Bret Easton</nom>
        <prenom>Ellis</prenom>
        <nationalité> américain</nationalité>
    </auteur>
    <titre>Lunar Park</titre>
    <description>Roman</description>
    <cover>livre6.jpg</cover>
    <date>2019</date>
    
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>
            Le héros du livre est Bret Easton Ellis qui narre, en guise d'introduction au roman, l'histoire de son fulgurant succès littéraire, de sa famille, de sa vie, de la drogue et de la débauche. Le roman débute au moment où l'écrivain se rachète une conduite en épousant l'actrice Jayne Dennis (dans la réalité Ellis n'aurait jamais été marié) et en s'installant dans une banlieue riche de la côte est américaine avec sa femme et son fils (reconnu après de multiples procès).
        </paragraphe>
        <paragraphe> 
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
            dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </paragraphe>
        
    </section>
</livre>

=== EB-Omar/Library/Books/livre7.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre7 -->
    
    <auteur>
        <nom>Chinua</nom>
        <prenom>Achebe</prenom>
        <nationalité>Nigérian</nationalité>
    </auteur>
    <titre>Tout s'effondre</titre>
    <description>Roman</description>
    <cover>livre7.jpg</cover>
    <date>1958</date>
    
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>
            Le protagoniste du roman, Okonkwo, est célèbre dans les villages d'Umuofia pour ses talents de lutteur, battant un lutteur surnommé Amalinze le chat (parce qu'il ne tombe jamais sur le dos). Okonkwo est fort, travailleur et s'efforce de ne montrer aucune faiblesse. Il veut faire oublier le souvenir de son père Unoka, de ses dettes impayées, de sa négligence envers sa femme et ses enfants, et de sa lâcheté à la vue du sang. Okonkwo travaille à bâtir sa richesse entièrement seul, car Unoka est mort d'une mort honteuse et ne lui a laissé que de nombreuses dettes. Il est aussi obsédé par sa masculinité, et tout petit compromis à ce sujet est rapidement renié. Par conséquent, il bat souvent ses femmes et ses enfants, et il est méchant avec ses voisins. Sa volonté d'échapper à l'héritage de son père le conduit à être riche, courageux et puissant parmi les gens de son village. C'est un leader de son village. Il a atteint une position dans sa société pour laquelle il s'est battu toute sa vie
        </paragraphe>
        <paragraphe> 
            test  test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test
        </paragraphe>
        
    </section>
</livre>

=== EB-Omar/Library/Books/livre9.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre9 -->
    
    <auteur>
        <nom>Henrik Johan</nom>
        <prenom>Ibsen</prenom>
        <nationalité>Norvégien</nationalité>
    </auteur>
    <titre>Une maison de poupée</titre>
    <description>Roman</description>
    <cover>livre9.jpg</cover>
    <date>1879</date>
    
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>
            Nora, personnage principal de la pièce, est mariée depuis huit ans au banquier Torvald Helmer, avec lequel elle a eu trois enfants. Son mari la traite comme une mineure, ne cessant de l'appeler son "alouette" ou son "petit écureuil" et de lui dicter ce qu'elle doit faire, considérant que c'est le rapport normal entre un homme et sa femme, comme le veut l'idéologie de l'époque.
            
            L'intrigue se greffe sur un événement qui s'est produit peu après leur mariage : le médecin de famille a annoncé à Nora que son mari était atteint d'une grave maladie et que le seul moyen de le sauver était de l'emmener se reposer en Italie, d'où il est effectivement revenu guéri. Mais le voyage coûtant cher et Nora n'en ayant pas les moyens, elle n'a trouvé d'autre recours que d'emprunter l'argent à Krogstad, un collègue de son mari, à l'insu de ce dernier et de faire un faux en écriture, sans avoir conscience de la gravité de son acte.
            
            Krogstad envoie une lettre expliquant tout à Helmer. Ce dernier réagit avec horreur, dégoût et colère. Il ne pense qu'à sa réputation, et qualifie l'amour qui a poussé Nora à agir comme elle l'a fait de "prétexte stupide".
            
            Peu après, une seconde lettre parvient à Helmer, contenant la reconnaissance de dette de sa femme : Krogstad renonce à rendre l'affaire publique. À la suite de quoi Helmer pardonne à sa femme. Mais la pièce ne s'arrête pas là : Nora quitte son mari pour mieux comprendre le monde et trouver ses propres réponses aux grandes questions de la vie. Dans l'optique d'un possible retour, elle impose une condition à son mari : "que leur vie en commun puisse devenir un mariage".
        </paragraphe>
        <paragraphe> 
            test  test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test
        </paragraphe>
        
    </section>
</livre>

=== EB-Omar/Library/Books/livre10.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre10 -->
    
    <auteur>
        <nom>Annie</nom>
        <prenom>Ernaux</prenom>
        <nationalité>française</nationalité>
    </auteur>
    <titre>Les Années</titre>
    <description>Roman</description>
    <cover>livre10.jpg</cover>
    <date>2009</date>
    
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>
            Le roman oscille entre des descriptions de photos décrivant l'autrice, prises entre 1941 et 2006, et une peinture de l'époque à laquelle ces photos ont été prises à travers les souvenirs qui se sont gravés dans l'esprit de l'autrice, choisis pour leur pertinence sociologique. Le roman brasse 60 ans d'histoire commune avec le récit de l'existence unique de l'autrice, mais l'autrice met à distance celle qu'elle fut par l'usage de la troisième personne. Son histoire est personnelle, impersonnelle et collective. A. Ernaux renouvelle le genre de l'autobiographie.
        </paragraphe>
        <paragraphe> 
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
            dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </paragraphe>
        
    </section>
</livre>
