=== EB-Omar/Library/Books/livre.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <!-- balises isolées --> <xsd:element name="titre" type="xsd:string"/> 
  <xsd:element
    name="description" type="xsd:string"/> <xsd:element name="cover" type="xsd:string"/>
    <xsd:element name="date" type="xsd:string"/> 
  <!-- balises d'un auteur --> <xsd:element name="nom" type="xsd:string"/> <xsd:element
    name="prenom" type="xsd:string"/> <xsd:element name="nationalité" type="xsd:string"/>
  <!-- balise auteur --> <xsd:element name="auteur"> <xsd:complexType> <xsd:sequence> <xsd:element
          ref="nom"/> <xsd:element ref="prenom"/> <xsd:element ref="nationalité"/> </xsd:sequence>
    </xsd:complexType> </xsd:element>     <xsd:element name="titre_s"
    type="xsd:string"/> <xsd:element name="paragraphe"/>
  <!-- balise sction --> <xsd:element name="section"> <xsd:complexType> <xsd:sequence> <xsd:element
          ref="titre_s"/> <xsd:element ref="paragraphe" maxOccurs="unbounded"/> </xsd:sequence>
    </xsd:complexType> </xsd:element> <xsd:element name="livre"> <xsd:complexType> <xsd:sequence>
          <xsd:element ref="auteur"/> <xsd:element ref="titre"/> <xsd:element ref="description"/>
          <xsd:element ref="cover"/> <xsd:element ref="date"/> 
          <xsd:element ref="section"/> </xsd:sequence> </xsd:complexType> </xsd:element> </xsd:schema>

=== EB-Omar/Library/Books/livre3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre3 -->
    
    <auteur>
        <nom>José</nom>
        <prenom>Rodrigues</prenom>
        <nationalité>Portugais</nationalité>
    </auteur>
    <titre>La formule de dieu</titre>
    <description>Roman</description>
    <cover>livre3.jpg</cover>
    <date>2012</date>
   
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>
            Tomas Noronha, professeur d'histoire spécialiste en cryptologie à l'université nouvelle de Lisbonne au Portugal, est sollicité par le Ministère de la Science iranien pour décrypter un manuscrit inédit d'Albert Einstein. La CIA est mise au courant de l'affaire et n'hésite pas à faire du professeur Noronha un agent double. Parallèlement, un des collègues de son père, physicien et ancien collaborateur d'Einstein, disparaît mystérieusement.
            
            C'est le début d'un récit qui va emmener le lecteur des rues de Téhéran au QG de la CIA, en passant par un monastère bouddhiste niché au cœur des montagnes tibétaines, à la rencontre des plus récentes théories de physique quantique et des textes fondamentaux de la sagesse universelle.
        </paragraphe>
        <paragraphe> 
            test  test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test
        </paragraphe>
        
    </section>
</livre>
