=== EB-Omar/Library/Books/livre.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <!-- balises isolées --> <xsd:element name="titre" type="xsd:string"/> 
  <xsd:element
    name="description" type="xsd:string"/> <xsd:element name="cover" type="xsd:string"/>
    <xsd:element name="date" type="xsd:string"/> 
  <!-- balises d'un auteur --> <xsd:element name="nom" type="xsd:string"/> <xsd:element
    name="prenom" type="xsd:string"/> <xsd:element name="nationalité" type="xsd:string"/>
  <!-- balise auteur --> <xsd:element name="auteur"> <xsd:complexType> <xsd:sequence> <xsd:element
          ref="nom"/> <xsd:element ref="prenom"/> <xsd:element ref="nationalité"/> </xsd:sequence>
    </xsd:complexType> </xsd:element>     <xsd:element name="titre_s"
    type="xsd:string"/> <xsd:element name="paragraphe"/>
  <!-- balise sction --> <xsd:element name="section"> <xsd:complexType> <xsd:sequence> <xsd:element
          ref="titre_s"/> <xsd:element ref="paragraphe" maxOccurs="unbounded"/> </xsd:sequence>
    </xsd:complexType> </xsd:element> <xsd:element name="livre"> <xsd:complexType> <xsd:sequence>
          <xsd:element ref="auteur"/> <xsd:element ref="titre"/> <xsd:element ref="description"/>
          <xsd:element ref="cover"/> <xsd:element ref="date"/> 
          <xsd:element ref="section"/> </xsd:sequence> </xsd:complexType> </xsd:element> </xsd:schema>

=== EB-Omar/Library/Books/livre2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre2 -->
    
    <auteur>
        <nom>Stendhal</nom>
        <prenom>Stendhal</prenom>
        <nationalité>Français</nationalité>
    </auteur>
    <titre>Le rouge et le noir</titre>
    <description>Roman</description>
    <cover>livre2.jpg</cover>
    <date>1830</date>
   
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>Le roman est divisé en deux parties : la première partie retrace le parcours de Julien Sorel en province, dans une petite ville nommée Verrières, puis à Besançon, et plus précisément son entrée chez les Rênal, et sa passion avec Louise de Rênal, de même que son séjour dans un séminaire ; la seconde partie porte sur la vie du héros à Paris comme secrétaire du marquis de La Mole, et la passion qu'il a avec sa fille, Mathilde.</paragraphe>
        <paragraphe> 
            test  test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test
        </paragraphe>
        
    </section>
</livre>

=== EB-Omar/Library/Books/livre1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre1 -->
    
    <auteur>
        <nom>Paulo </nom>
        <prenom>Coelho</prenom>
        <nationalité>brésilien</nationalité>
    </auteur>
    <titre>Adultère</titre>
    <description>Roman</description>
    <cover>livre1.jpg</cover>
    <date>2014</date>
    
   
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe> Dans Adultère, Paulo Coelho raconte le destin d’une femme mariée, Linda, journaliste mère de famille comblée. Or, cette petite vie bien rangée l’ennuie. Ce n’est que, lorsqu’au hasard d’une interview, elle retrouve un ancien flirt de jeunesse devenu politicien, qu’elle renouera avec la passion.
            
            Elle se plaint, "vois ce que je deviens !" Serre-moi bien, dans nôtre pays serein. C'est l'histoire de l'arrogance d'une femme, l'histoire de ses aventures, ses découvertes, de ses errances sexuelles; de ses désordres; quand le temps l'a enrichie, protégée, sécurisée dans son statut, ses affections, sa situation.
            
            C'est le récit de ses surenchères, sexuelles, caractérielles, consuméristes. Elle est journaliste, il est haut placé... L'autre aussi, qui lui fera découvrir sa face sombre, ses désirs mimétiques non souhaités, ses actions éloignées de ses vrais désirs. Elle retrouvera un autre équilibre après avoir évolué et bien profité des circonstances, bien à l'abri de sa prudence et de son plaisir primaire, malgré ses déconvenues. Et ce dans le cocon protecteur de l'opulence et de la distraction ; pour vivre son spleen, ses fantasmes, son épanouissement aussi... pense-t-elle.
        </paragraphe>
        <paragraphe> 
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
            dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </paragraphe>
    </section>
</livre>

=== EB-Omar/Library/Books/livre8.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre8 -->
    
    <auteur>
        <nom>Honoré de</nom>
        <prenom>Balzac</prenom>
        <nationalité>Français</nationalité>
    </auteur>
    <titre>Le Père Goriot</titre>
    <description>Roman</description>
    <cover>livre8.jpg</cover>
    <date>1842</date>
    
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>
            Le roman s'ouvre en 1819, avec la description sordide et répugnante de la maison Vauquer, une pension parisienne située dans la rue Neuve-Sainte-Geneviève, appartenant à la veuve Vauquer. Plusieurs résidents s'y côtoient, dont Eugène de Rastignac, jeune étudiant en droit, un mystérieux personnage un peu rustre et grossier nommé Vautrin et un ancien vermicellier (fabricant de pâtes et de pain) ayant fait fortune pendant la Révolution, maintenant retraité, complètement désargenté et veuf, surnommé le père Goriot par la veuve Vauquer, frustrée dans ses intentions de mariage avec lui à l'époque où il était arrivé à la pension, riche, bien mis et en possession de beaucoup de mobilier. La plupart des pensionnaires se sont mis à l'appeler ainsi aussi, le tournant en ridicule et le considérant comme sénile et diminué. Logent également dans la pension d'autres personnes, comme Melle Michonneau, Victorine Taillefer, ou encore Horace Bianchon.
        </paragraphe>
        <paragraphe> 
            test  test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test
        </paragraphe>
        
    </section>
</livre>

=== EB-Omar/Library/Books/livre4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="livre.xsl"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="livre.xsd">
    <!-- livre4 -->
    
    <auteur>
        <nom>George</nom>
        <prenom> Martin</prenom>
        <nationalité>américain</nationalité>
    </auteur>
    <titre>Le Trône de fer </titre>
    <description>Roman</description>
    <cover>livre4.jpg</cover>
    <date>1996</date>
    
    <section>
        <titre_s>Résumé</titre_s>
        <paragraphe>L'histoire se situe à une époque médiévale, sur un continent appelé Westeros au sein du royaume des Sept Couronnes. Ce royaume est dirigé par Robert Baratheon depuis qu'il a chassé du trône le roi fou, Aerys Targaryen.
            
            Au début de l'histoire, le roi voyage vers le nord de son royaume pour proposer le poste de Main du Roi (sorte de premier ministre) à son grand ami Eddard Stark, le seigneur de Winterfell. Celui-ci accepte et se rend à Port-Réal, la capitale du royaume pour exercer son pouvoir. Il tente de déjouer les complots, tandis que sur un autre continent, de l'autre côté du Détroit, Daenerys Targaryen, la fille du roi déchu, rêve de reconquérir le trône de son père, le Trône de fer.</paragraphe>
        
        <paragraphe> 
            test  test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test
        </paragraphe>
    </section>
</livre>
